AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Layout/LineLength:
  Exclude:
    - '*.gemspec'

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
  Max: 15
